sonar.projectKey=fuchi-no-dokuneko_Useful_shell_script
sonar.organization=fuchi-no-dokuneko
sonar.host.url=https://sonarcloud.io
sonar.projectName=Useful_shell_script
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.exclusions=.github/**,**/*.md
sonar.coverageReportPaths=coverage/sonar-generic-coverage.xml
